default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  username: yoshikazu
  password: Kazu83571919
  host: localhost
development:
  <<: *default
  database: tweet_app_development
test:
  <<: *default
  database: tweet_app_test

production:
  <<: *default
  database: tweet_app_production
