default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  username: rails_tweet_app
  password: U3Cc5VR8KY
  host: localhost
development:
  <<: *default
  database: tweet_app_development
test:
  <<: *default
  database: tweet_app_test

production:
  <<: *default
  database: tweet_app_production
